language: python
install: 
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::=--force-confnew install dsc21
  - sudo service cassandra stop
  - sudo rm -rf /var/lib/cassandra/*
  - sudo service cassandra start
  - sleep 10
  - ps aux
  - netstat -lntp
  - cat /var/log/cassandra/system.log
  - sudo apt-get install libev4 libev-dev
  - pip install blist
  - pip install cassandra-driver
script: 
  - ./tests/run_tests.sh
