language: python
install: 
  - echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y --force-yes install dsc21
  - sudo service cassandra start
  - pip install cassandra-driver
script: 
  - ./tests/run_tests.sh
